In [138]:
import pandas as pd

dataset = pd.read_csv("Placement.csv")
dataset.drop('sl_no', axis=1)
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [ ]:
# adding mean, median, mode, percentiles (Q1, Q2, Q3, Q4)
from collections import defaultdict

num_columns = dataset.select_dtypes(include="number")
col_names = num_columns.columns
description = num_columns.describe()

calculations = defaultdict(
    dict
)  # defaultdict --> Collector function for dynamic dictionary manipulation

for column in col_names:
    col = num_columns[column]
    median = col.median()

    num_columns.loc[col.isna(), column] = median  # Replacing NaN with median

    calculations[column] = {
        "Mean": col.mean(),
        "Median": median,
        "Mode": col.mode()[0],
        "Q1-25%": description[column]["25%"],
        "Q2-50%": description[column]["50%"],
        "Q3-75%": description[column]["75%"],
        "Q4-100%": description[column]["max"],
    }
print(num_columns)
calculations

     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
0        1  67.00  91.00     58.00     55.0  58.80  270000.0
1        2  79.33  78.33     77.48     86.5  66.28  200000.0
2        3  65.00  68.00     64.00     75.0  57.80  250000.0
3        4  56.00  52.00     52.00     66.0  59.43  265000.0
4        5  85.80  73.60     73.30     96.8  55.50  425000.0
..     ...    ...    ...       ...      ...    ...       ...
210    211  80.60  82.00     77.60     91.0  74.49  400000.0
211    212  58.00  60.00     72.00     74.0  53.62  275000.0
212    213  67.00  67.00     73.00     59.0  69.72  295000.0
213    214  74.00  66.00     58.00     70.0  60.23  204000.0
214    215  62.00  58.00     53.00     89.0  60.22  265000.0

[215 rows x 7 columns]

defaultdict(dict,
            {'sl_no': {'Mean': np.float64(108.0),
              'Median': np.float64(108.0),
              'Mode': np.int64(1),
              'Q1-25%': np.float64(54.5),
              'Q2-50%': np.float64(108.0),
              'Q3-75%': np.float64(161.5),
              'Q4-100%': np.float64(215.0)},
             'ssc_p': {'Mean': np.float64(67.30339534883721),
              'Median': np.float64(67.0),
              'Mode': np.float64(62.0),
              'Q1-25%': np.float64(60.599999999999994),
              'Q2-50%': np.float64(67.0),
              'Q3-75%': np.float64(75.7),
              'Q4-100%': np.float64(89.4)},
             'hsc_p': {'Mean': np.float64(66.33316279069768),
              'Median': np.float64(65.0),
              'Mode': np.float64(63.0),
              'Q1-25%': np.float64(60.9),
              'Q2-50%': np.float64(65.0),
              'Q3-75%': np.float64(73.0),
              'Q4-100%': np.float64(97.7)},
             'degree_p': {'Mean': np.float64(66.37018604651163),
              'Median': np.float64(66.0),
              'Mode': np.float64(65.0),
              'Q1-25%': np.float64(61.0),
              'Q2-50%': np.float64(66.0),
              'Q3-75%': np.float64(72.0),
              'Q4-100%': np.float64(91.0)},
             'etest_p': {'Mean': np.float64(72.10055813953488),
              'Median': np.float64(71.0),
              'Mode': np.float64(60.0),
              'Q1-25%': np.float64(60.0),
              'Q2-50%': np.float64(71.0),
              'Q3-75%': np.float64(83.5),
              'Q4-100%': np.float64(98.0)},
             'mba_p': {'Mean': np.float64(62.278186046511635),
              'Median': np.float64(62.0),
              'Mode': np.float64(56.7),
              'Q1-25%': np.float64(57.945),
              'Q2-50%': np.float64(62.0),
              'Q3-75%': np.float64(66.255),
              'Q4-100%': np.float64(77.89)},
             'salary': {'Mean': np.float64(288655.4054054054),
              'Median': np.float64(265000.0),
              'Mode': np.float64(300000.0),
              'Q1-25%': np.float64(240000.0),
              'Q2-50%': np.float64(265000.0),
              'Q3-75%': np.float64(300000.0),
              'Q4-100%': np.float64(940000.0)}})

In [ ]:
# add iqr, lower_range, higher_range
for column in num_columns.columns:
    q1 = calculations[column]["Q1-25%"]
    q3 = calculations[column]["Q3-75%"]
    iqr = q3 - q1
    calculations[column]["IQR"] = iqr
    calculations[column]["lower_outlier_range"] = q1 - 1.5 * iqr
    calculations[column]["higher_outlier_range"] = q3 + 1.5 * iqr

In [141]:
pd.DataFrame(calculations)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
Mode,1.0,62.000000,63.000000,65.000000,60.000000,56.700000,300000.000000
Q1-25%,54.5,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
Q2-50%,108.0,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
Q3-75%,161.5,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
Q4-100%,215.0,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000
IQR,107.0,15.100000,12.100000,11.000000,23.500000,8.310000,60000.000000
lower_outlier_range,-106.0,37.950000,42.750000,44.500000,24.750000,45.480000,150000.000000
higher_outlier_range,322.0,98.350000,91.150000,88.500000,118.750000,78.720000,390000.000000

In [143]:
# adding possible outliers count
for column in num_columns:
    lower_outlier = calculations[column]["lower_outlier_range"]
    higher_outlier = calculations[column]["higher_outlier_range"]
    col = num_columns[column]
    calculations[column]["outliers_count"] = col[
        (col < lower_outlier) | (col > higher_outlier)
    ].count()

calculated = pd.DataFrame(calculations)
calculated

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
Mode,1.0,62.000000,63.000000,65.000000,60.000000,56.700000,300000.000000
Q1-25%,54.5,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
Q2-50%,108.0,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
Q3-75%,161.5,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
Q4-100%,215.0,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000
IQR,107.0,15.100000,12.100000,11.000000,23.500000,8.310000,60000.000000
lower_outlier_range,-106.0,37.950000,42.750000,44.500000,24.750000,45.480000,150000.000000
higher_outlier_range,322.0,98.350000,91.150000,88.500000,118.750000,78.720000,390000.000000
possible_outliers,0.0,0.000000,8.000000,1.000000,0.000000,0.000000,15.000000
outliers_count,0.0,0.000000,8.000000,1.000000,0.000000,0.000000,15.000000

In [147]:
# Replace Outliers
for col in num_columns:
    lower = calculations[col]['lower_outlier_range']
    higher = calculations[col]['higher_outlier_range']
    num_columns[col] = num_columns[col].clip(lower, higher)  # clip() method bounds the values between lower and higher
num_columns

     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
0        1  67.00  91.00     58.00     55.0  58.80  270000.0
1        2  79.33  78.33     77.48     86.5  66.28  200000.0
2        3  65.00  68.00     64.00     75.0  57.80  250000.0
3        4  56.00  52.00     52.00     66.0  59.43  265000.0
4        5  85.80  73.60     73.30     96.8  55.50  390000.0
..     ...    ...    ...       ...      ...    ...       ...
210    211  80.60  82.00     77.60     91.0  74.49  390000.0
211    212  58.00  60.00     72.00     74.0  53.62  275000.0
212    213  67.00  67.00     73.00     59.0  69.72  295000.0
213    214  74.00  66.00     58.00     70.0  60.23  204000.0
214    215  62.00  58.00     53.00     89.0  60.22  265000.0

[215 rows x 7 columns]

In [153]:
# verifying data after replacing outliers

for column in num_columns:
    lower = calculations[column]["lower_outlier_range"]
    higher = calculations[column]["higher_outlier_range"]
    outlier_count = num_columns[column][
        (num_columns[column] < lower) | (num_columns[column] > higher)
    ].count()
    calculations[column]["revised_outlier_count"] = outlier_count

pd.DataFrame(calculations)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
Mode,1.0,62.000000,63.000000,65.000000,60.000000,56.700000,300000.000000
Q1-25%,54.5,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
Q2-50%,108.0,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
Q3-75%,161.5,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
Q4-100%,215.0,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000
IQR,107.0,15.100000,12.100000,11.000000,23.500000,8.310000,60000.000000
lower_outlier_range,-106.0,37.950000,42.750000,44.500000,24.750000,45.480000,150000.000000
higher_outlier_range,322.0,98.350000,91.150000,88.500000,118.750000,78.720000,390000.000000
possible_outliers,0.0,0.000000,8.000000,1.000000,0.000000,0.000000,15.000000
outliers_count,0.0,0.000000,8.000000,1.000000,0.000000,0.000000,15.000000
revised_outlier_count,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000