In [368]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

pio.renderers.default = 'vscode'

In [369]:
df = pd.read_csv('zomato_bangalore_dataset.csv')
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [370]:
# Remove unwanted columns (url, dish_liked, reviews_list, menu_item, listed_in(type), listed_in(city))

df.drop(
    [
        "address",
        "url",
        "phone",
        "dish_liked",
        "reviews_list",
        "menu_item",
        "listed_in(type)",
        "listed_in(city)",
    ],
    axis=1,
    inplace=True,
)

In [371]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600

In [372]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         51717 non-null  str
 1   online_order                 51717 non-null  str
 2   book_table                   51717 non-null  str
 3   rate                         43942 non-null  str
 4   votes                        51717 non-null  int64
 5   location                     51696 non-null  str
 6   rest_type                    51490 non-null  str
 7   cuisines                     51672 non-null  str
 8   approx_cost(for two people)  51371 non-null  str
dtypes: int64(1), str(8)
memory usage: 3.6 MB

In [373]:
# checking null values
df.isna().sum()

name                              0
online_order                      0
book_table                        0
rate                           7775
votes                             0
location                         21
rest_type                       227
cuisines                         45
approx_cost(for two people)     346
dtype: int64

In [374]:
df[df['location'].isna()].head(5)

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people)
1662,Papa Khan Rasoi,No,No,NaN,0,NaN,NaN,NaN,NaN
9874,Papa Khan Rasoi,No,No,NaN,0,NaN,NaN,NaN,NaN
13693,Mohabbat Desi Restaurant,No,No,NaN,0,NaN,NaN,NaN,NaN
16351,Desi Chatkara,No,No,NaN,0,NaN,NaN,NaN,NaN
26432,New Taj Biryani Centre,No,No,NaN,0,NaN,NaN,NaN,NaN

In [375]:
# removing reduntant rows where all features are Nan except 'name'

df = df[~ df['location'].isna()]

In [376]:
df.isna().sum()

name                              0
online_order                      0
book_table                        0
rate                           7754
votes                             0
location                          0
rest_type                       206
cuisines                         24
approx_cost(for two people)     325
dtype: int64

In [377]:
df[df['approx_cost(for two people)'].isna()]

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people)
1768,Innate,No,No,NaN,0,JP Nagar,Delivery,Beverages,NaN
1795,Super Chef's (New Royal treat),No,No,NaN,0,Bannerghatta Road,Quick Bites,"North Indian, Chinese, South Indian",NaN
3069,Super Chef's (New Royal treat),No,No,-,0,Bannerghatta Road,Quick Bites,"North Indian, Chinese, South Indian",NaN
3774,The Hub - Ibis Bengaluru,No,No,3.9/5,237,Marathahalli,Bar,Finger Food,NaN
3954,North Indian Kitchen,No,No,3.2/5,13,HSR,Takeaway,North Indian,NaN
...,...,...,...,...,...,...,...,...,...
50940,Cinnabon,No,No,4.0 /5,80,Whitefield,Quick Bites,"Beverages, American, Bakery",NaN
51233,Mayas kitchen,No,No,NaN,0,Whitefield,Casual Dining,"South Indian, Chinese, Chettinad",NaN
51247,Mast Kalandar,No,No,2.6 /5,76,Whitefield,Casual Dining,North Indian,NaN
51271,Karavalli Food Court,No,No,3.2 /5,4,Whitefield,Casual Dining,South Indian,NaN
51641,Andhra Spices,No,No,3.2 /5,4,Brookefield,Quick Bites,"Andhra, Chinese, South Indian",NaN

In [378]:
# removing rows with no price and no ratings.
df = df[~((df["approx_cost(for two people)"].isna()) & (df["votes"] == 0))]

In [379]:
df.isna().sum()

name                              0
online_order                      0
book_table                        0
rate                           7684
votes                             0
location                          0
rest_type                       206
cuisines                         22
approx_cost(for two people)     250
dtype: int64

In [380]:
# remove duplicate records
df = df.drop_duplicates()

In [381]:
df.duplicated().sum()

np.int64(0)

In [382]:
df[df['approx_cost(for two people)'].isna()].head(10)

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people)
3774,The Hub - Ibis Bengaluru,No,No,3.9/5,237,Marathahalli,Bar,Finger Food,NaN
3954,North Indian Kitchen,No,No,3.2/5,13,HSR,Takeaway,North Indian,NaN
4040,Only Parathas,No,No,3.3/5,6,HSR,"Takeaway, Delivery",North Indian,NaN
5797,Priya's Punjabi,No,No,3.8/5,33,Koramangala 8th Block,Casual Dining,North Indian,NaN
8351,Krazy Factory,No,No,4.0/5,431,Koramangala 5th Block,Cafe,"Cafe, Continental, Chinese",NaN
8586,Seasons,No,No,3.8/5,500,Bannerghatta Road,Casual Dining,"North Indian, South Indian, Chinese, Seafood, ...",NaN
9648,The Enav Bowl,No,No,3.8/5,20,Koramangala 5th Block,Quick Bites,"Healthy Food, Beverages, Mexican, Burger, Italian",NaN
10089,Innate,No,No,3.3/5,7,Koramangala 7th Block,Delivery,Beverages,NaN
10218,Kesar Sweet Shop and Fast Food,No,No,4.0 /5,213,BTM,Quick Bites,"North Indian, South Indian, Chinese, Street Fo...",NaN
10238,Pabrai's Fresh and Naturelle Icecreams,No,No,3.7 /5,118,BTM,Dessert Parlor,"Ice Cream, Desserts",NaN

In [383]:
df['cuisines'].value_counts()

cuisines
North Indian                               1319
North Indian, Chinese                       996
South Indian                                904
Biryani                                     421
Bakery, Desserts                            388
                                           ...
Italian, North Indian, Continental, BBQ       1
Tibetan, Nepalese                             1
North Indian, Street Food, Biryani            1
Chinese, Mughlai                              1
North Indian, Chinese, Arabian, Momos         1
Name: count, Length: 2722, dtype: int64

In [384]:
# TODO:
# 
# 1. replace column names with meaningful name.
#
# 2. removal of redundant information
#   2.1. redundant columns => "url", "dish_liked", "reviews_list", "menu_item","listed_in(type)","listed_in(city)"
#   2.2. remove duplicate rows
#   2.3. remove records with no price and ratings
# 
# 3. replace null values
#   3.1.    rates -> 0
#   3.2.    phone -> Nil
#   3.3.    rest_type -> replace with Nil
#   3.4.    cuisines -> replace with Nil
#   3.5.    approximate cost -> replace with 0
#
# 4. Handling multiple values:
#   A restaurant has multiple ['cuisine', 'rest_type'] types. Split the multiple items and replace with most occured
#   reducing multiple types for better performance.

In [385]:
# replace with meaning column name
df = df.rename(columns={"approx_cost(for two people)": "price"})
df.head(5)

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,price
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600

In [386]:
df.isna().sum()

name               0
online_order       0
book_table         0
rate            2684
votes              0
location           0
rest_type         88
cuisines          16
price             98
dtype: int64

In [387]:
# split the rate column and convert to float

df['rate'] = df['rate'].replace(['NEW', '-'], None)
df['rate'] = df['rate'].str.split('/').str[0].astype(float)

# Replace NaN with 0
df["rate"] = df["rate"].fillna(0)

In [388]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,price
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600

In [389]:
# handling multiple rest_types
# replacing with 1st type
df["rest_type"] = df["rest_type"].str.split(",").str[0].str.strip()

# reduced multiple restaurant types
qb = ["Bakery", "Beverage Shop", "Food Court", "Pop Up", "Kiosk", "Food Truck"]
cd = ["Fine Dining", "Mess", "Bhojanalya", "Dhaba", "Lounge"]
bar = ["Bar", "Pub", "Microbrewery", "Club"]
dessert = ["Sweet Shop", "Confectionery", "Dessert Parlor"]

df["rest_type"] = df["rest_type"].replace(qb, "Quick Bites")
df["rest_type"] = df["rest_type"].replace(cd, "Casual Dining")
df["rest_type"] = df["rest_type"].replace(bar, "Bar")
df["rest_type"] = df["rest_type"].replace(dessert, "Dessert")
df["rest_type"] = df["rest_type"].replace(["Takeaway", "Delivery"], "Delivery/Takeaway")

# replace NaN with 'Unknown'
df["rest_type"] = df["rest_type"].fillna("Unknown")

In [390]:
df['rest_type'].value_counts()

rest_type
Quick Bites          10309
Casual Dining         6062
Delivery/Takeaway     2652
Cafe                  1502
Dessert               1468
Bar                    836
Unknown                 88
Name: count, dtype: int64

In [391]:
# Handling multiple cuisines

df["cuisines"] = df["cuisines"].str.split(",").str[0].str.strip()

continetal = [
    "Mediterranean",
    "Iranian",
    "Australian",
    "German",
    "Spanish",
    "Middle Eastern",
    "South American",
    "French",
    "Steak",
    "Turkish",
    "Lebanese",
    "Portuguese",
    "African",
    "Italian",
    "Mexican",
    "BBQ",
    "Belgian",
    "British",
    "European",
    "Russian",
    "Arabian",
    "American",
    "Parsi",
]
asian = [
    "Chinese",
    "Indonesian",
    "Singaporean",
    "Sushi",
    "Burmese",
    "Tibetan",
    "Nepalese",
    "Momos",
    "Thai",
    "Japanese",
    "Malaysian",
    "Korean",
    "North Eastern",
    "Vietnamese",
]
north_indian = [
    "Mughlai",
    "Afghan",
    "Kashmiri",
    "Awadhi",
    "Lucknowi",
    "Bengali",
    "Kebab",
    "Rajasthani",
    "Modern Indian",
    "Bohri",
]
south_indian = [
    "Biryani",
    "Charcoal Chicken",
    "Hyderabadi",
    "Chettinad",
    "Andhra",
    "Mangalorean",
    "Maharashtrian",
    "Tamil",
    "Roast Chicken",
    "Kerala",
    "Healthy Food",
    "Salad",
]
east_indian = ["Oriya", "Bihari", "Assamese", "Naga", "Mithai"]
west_indian = ["Maharashtrian", "Goan", "Konkan", "Gujarati"]
fast_food = [
    "Street Food",
    "Rolls",
    "Finger Food",
    "Pizza",
    "Sandwich",
    "Burger",
    "Salad",
    "Bakery",
]
cafe = ["Coffee", "Desserts", "Ice Cream", "Tea", "Bar Food", "Drinks Only", "Juices"]

df["cuisines"] = df["cuisines"].replace(continetal, "Continental")
df["cuisines"] = df["cuisines"].replace(asian, "Asian")
df["cuisines"] = df["cuisines"].replace(north_indian, "North Indian")
df["cuisines"] = df["cuisines"].replace(south_indian, "South Indian")
df["cuisines"] = df["cuisines"].replace(east_indian, "East Indian")
df["cuisines"] = df["cuisines"].replace(west_indian, "West Indian")
df["cuisines"] = df["cuisines"].replace(cafe, "Cafe")
df["cuisines"] = df["cuisines"].replace(fast_food, "Fast Food")

# replace NaN with Unknown
df["cuisines"] = df["cuisines"].fillna("Unknown")

In [392]:
df["cuisines"].value_counts()

cuisines
North Indian    5914
South Indian    5283
Fast Food       3507
Cafe            3067
Continental     2111
Asian           1821
Beverages        618
East Indian      376
Seafood          162
West Indian       42
Unknown           16
Name: count, dtype: int64

In [393]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,price
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,North Indian,800
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,Asian,800
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,Cafe,Cafe,800
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,South Indian,300
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,North Indian,600

In [394]:
df.isna().sum()

name             0
online_order     0
book_table       0
rate             0
votes            0
location         0
rest_type        0
cuisines         0
price           98
dtype: int64

In [395]:
# replace NaN in price

# removing comma from 4,100 
df['price'] = df['price'].str.replace(',','')

# fill NaN with 0
df['price'] = df['price'].fillna(0)

# convert type to int
df['price'] = df['price'].astype(int)

In [396]:
df.info()

<class 'pandas.DataFrame'>
Index: 22917 entries, 0 to 51714
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          22917 non-null  str
 1   online_order  22917 non-null  str
 2   book_table    22917 non-null  str
 3   rate          22917 non-null  float64
 4   votes         22917 non-null  int64
 5   location      22917 non-null  str
 6   rest_type     22917 non-null  object
 7   cuisines      22917 non-null  object
 8   price         22917 non-null  int64
dtypes: float64(1), int64(2), object(2), str(4)
memory usage: 1.7+ MB

In [397]:
# encoding online_order, book_table to 0,1
df['online_order'] = df['online_order'].map({"Yes":1, "No": 0})
df['book_table'] = df['book_table'].map({"Yes":1, "No": 0})

In [398]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,price
0,Jalsa,1,1,4.1,775,Banashankari,Casual Dining,North Indian,800
1,Spice Elephant,1,0,4.1,787,Banashankari,Casual Dining,Asian,800
2,San Churro Cafe,1,0,3.8,918,Banashankari,Cafe,Cafe,800
3,Addhuri Udupi Bhojana,0,0,3.7,88,Banashankari,Quick Bites,South Indian,300
4,Grand Village,0,0,3.8,166,Basavanagudi,Casual Dining,North Indian,600

In [399]:
# saving preprocessed data

df.to_csv('zomato_preprocessed_dataset.csv', index=False)