In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv("files/Zomato_Mumbai_Dataset.csv", delimiter='|')
df.head()

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Mumbai,First International Financial Centre-- Bandra ...,https://www.zomato.com/mumbai/hitchki-bandra-k...,1,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mumbai,Mahim,https://www.zomato.com/mumbai/baba-falooda-mah...,1,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Mumbai,Juhu,https://www.zomato.com/mumbai/chin-chin-chu-ju...,1,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/butterfly-high-b...,1,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/bkc-dive-bandra-...,1,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

In [3]:
# basic data informations
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15081 entries, 0 to 15080
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             15081 non-null  str
 1   PRICE            15080 non-null  str
 2   CUSINE_CATEGORY  15079 non-null  str
 3   CITY             15080 non-null  str
 4   REGION           15080 non-null  str
 5   URL              15080 non-null  str
 6   PAGE NO          15080 non-null  str
 7   CUSINE TYPE      15080 non-null  str
 8   TIMING           15015 non-null  str
 9   RATING_TYPE      14070 non-null  str
 10  RATING           15080 non-null  str
 11  VOTES            15080 non-null  str
dtypes: str(12)
memory usage: 1.4 MB

In [4]:
# check redundant records

red_data = df['PAGE NO'] == 'PAGE NO'
red_data
df[red_data]

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
31,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
47,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
63,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
79,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
...,...,...,...,...,...,...,...,...,...,...,...,...
15000,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15016,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15032,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15048,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15064,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES

In [5]:
# removing redundant records
df = df[~red_data]

In [6]:
# removing unwanted columns

df.drop(["URL", "PAGE NO", "CITY"], axis=1, inplace=True)
df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

In [7]:
# check null values

df.isna().sum()

NAME                  0
PRICE                 1
CUSINE_CATEGORY       2
REGION                1
CUSINE TYPE           1
TIMING               66
RATING_TYPE        1011
RATING                1
VOTES                 1
dtype: int64

In [8]:
df[df['CUSINE_CATEGORY'].isna()]

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
7338,Mother's Taste,400,NaN,Bhandup,none,11am to 11pm(Mon-Sun),Good,3.5,57
15080,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# removing the record '15080'

df.drop(labels=15080, axis=0, inplace=True)

In [10]:
# verify null once again
df.isna().sum()

NAME                  0
PRICE                 0
CUSINE_CATEGORY       1
REGION                0
CUSINE TYPE           0
TIMING               65
RATING_TYPE        1010
RATING                0
VOTES                 0
dtype: int64

In [11]:
# replace null values with 'NA'

df.fillna('NA', inplace=True).head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

In [12]:
df.isna().sum()

NAME               0
PRICE              0
CUSINE_CATEGORY    0
REGION             0
CUSINE TYPE        0
TIMING             0
RATING_TYPE        0
RATING             0
VOTES              0
dtype: int64

In [13]:
df.info()

# from the below information the numerical columns are also in the form of String.

<class 'pandas.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  str
 1   PRICE            14138 non-null  str
 2   CUSINE_CATEGORY  14138 non-null  str
 3   REGION           14138 non-null  str
 4   CUSINE TYPE      14138 non-null  str
 5   TIMING           14138 non-null  str
 6   RATING_TYPE      14138 non-null  str
 7   RATING           14138 non-null  str
 8   VOTES            14138 non-null  str
dtypes: str(9)
memory usage: 1.1 MB

In [14]:
# convert numerical column from str to numerical

for name in ['RATING', 'PRICE', 'VOTES']:
    df[name] = pd.to_numeric(df[name], errors='coerce').fillna(0)

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  str
 1   PRICE            14138 non-null  int64
 2   CUSINE_CATEGORY  14138 non-null  str
 3   REGION           14138 non-null  str
 4   CUSINE TYPE      14138 non-null  str
 5   TIMING           14138 non-null  str
 6   RATING_TYPE      14138 non-null  str
 7   RATING           14138 non-null  float64
 8   VOTES            14138 non-null  float64
dtypes: float64(2), int64(1), str(6)
memory usage: 1.1 MB

In [16]:
df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529.0
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723.0
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337.0
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200.0
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995.0

In [17]:
# working with timing column

df['TIMING'].value_counts()

TIMING
11am to 11pm(Mon-Sun)                               1192
11am to 12midnight(Mon-Sun)                          632
12noon to 12midnight(Mon-Sun)                        467
11am to 1130pm(Mon-Sun)                              309
10am to 10pm(Mon-Sun)                                267
                                                    ...
9am to 9pm(Mon-Sat),9am to 10pm(Sun)                   1
Closed(Mon),7pm to 1130pm(Tue-Fri),1230pm to ...       1
1230pm to 330pm,730pm to 11pm(Mon),1230pm...           1
12noon to 4pm,730pm to 430am(Mon-Sun)                  1
8am to 11pm,12midnight to 115am(Mon-Sun)               1
Name: count, Length: 2551, dtype: int64

In [18]:
# splitting the TIMING column

temp = df["TIMING"].str.split("(", n=1, expand=True)

In [19]:
df['TIMING'] = temp[0]
df['DAYS_OPEN'] = temp[1]

In [20]:
df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun)
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun)
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun)
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun)
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995.0,Mon-Sun)

In [21]:
df["DAYS_OPEN"] = df["DAYS_OPEN"].str.replace(")", "", regex=False)

In [22]:
# check null values in DAYS_OPEN column
df['DAYS_OPEN'].isna().sum()

np.int64(160)

In [23]:
df['DAYS_OPEN'] = df['DAYS_OPEN'].fillna('NA')

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  str
 1   PRICE            14138 non-null  int64
 2   CUSINE_CATEGORY  14138 non-null  str
 3   REGION           14138 non-null  str
 4   CUSINE TYPE      14138 non-null  str
 5   TIMING           14138 non-null  str
 6   RATING_TYPE      14138 non-null  str
 7   RATING           14138 non-null  float64
 8   VOTES            14138 non-null  float64
 9   DAYS_OPEN        14138 non-null  str
dtypes: float64(2), int64(1), str(7)
memory usage: 1.2 MB

In [25]:
# removing restaurant records with rating or votes is 0

useless_data = (df["RATING"] < 1) | (df["VOTES"] < 1)
useless_data

0        False
1        False
2        False
3        False
4        False
         ...
15075    False
15076    False
15077    False
15078    False
15079    False
Length: 14138, dtype: bool

In [26]:
df = df[~useless_data]
df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995.0,Mon-Sun

In [27]:
# working on rating type column

df['RATING_TYPE'].value_counts()

RATING_TYPE
Average          5111
Good             4330
Very Good        1137
Excellent          95
Poor               47
Veľmi dobré         6
Skvělá volba        4
Dobrze              4
Bardzo dobrze       3
Muito Bom           2
Bom                 2
Buono               2
İyi                 2
Bueno               2
Ortalama            2
Průměr              2
Priemer             2
Dobré               2
Promedio            2
Velmi dobré         1
Excelente           1
Çok iyi             1
Baik                1
Média               1
Skvělé              1
Biasa               1
Sangat Baik         1
Muy Bueno           1
Media               1
Name: count, dtype: int64

In [28]:
rating_map = {
    # excellent
    "Excellent": "Excellent",
    "Excelente": "Excellent",
    # very good
    "Very Good": "Very Good",
    "Veľmi dobré": "Very Good",
    "Velmi dobré": "Very Good",
    "Bardzo dobrze": "Very Good",
    "Muito Bom": "Very Good",
    "Muy Bueno": "Very Good",
    "Sangat Baik": "Very Good",
    "Çok iyi": "Very Good",
    # good
    "Good": "Good",
    "Bom": "Good",
    "Bueno": "Good",
    "Buono": "Good",
    "İyi": "Good",
    "Baik": "Good",
    "Skvělá volba": "Good",
    "Dobré": "Good",
    "Dobrze": "Good",
    "Skvělé": "Good",
    # average
    "Average": "Average",
    "Ortalama": "Average",
    "Promedio": "Average",
    "Média": "Average",
    "Media": "Average",
    "Priemer": "Average",
    "Průměr": "Average",
    "Biasa": "Average",
    # poor
    "Poor": "Poor",
}

df["RATING_TYPE"] = df["RATING_TYPE"].map(rating_map)

In [29]:
df['RATING_TYPE'].value_counts()

RATING_TYPE
Average      5122
Good         4350
Very Good    1152
Excellent      96
Poor           47
Name: count, dtype: int64

In [30]:
# working on region column
df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Very Good,4.4,5995.0,Mon-Sun

In [31]:
# removing unwanted characters from region upto --
## eg. Aureole Hotel-- Andheri East => Andheri East
df["REGION"] = df["REGION"].replace("[a-zA-Z].+--", "", regex=True)
df["REGION"]

0         Bandra Kurla Complex
1                        Mahim
2                         Juhu
3         Bandra Kurla Complex
4         Bandra Kurla Complex
                 ...
15075             Andheri West
15076           Kandivali West
15077              Lower Parel
15078           Kandivali West
15079               Malad West
Name: REGION, Length: 10767, dtype: str

In [32]:
# removing north, south, east, west


df['REGION'] = df['REGION'].str.lower().replace(r'\b(north|south|east|west)\b', '', regex=True)
df['REGION'].value_counts()

REGION
 thane        712
 andheri      409
mira road     405
malad         370
kandivali     361
             ...
 chakala        1
 goregaon       1
 parel          1
 dadar          1
 bhayandar      1
Name: count, Length: 148, dtype: int64

In [33]:
# replacing small regions to known region 
df['REGION'] = df['REGION'].str.replace('Bandra Kurla Complex','Bandra',regex=True)
df['REGION'] = df['REGION'].str.replace('CBD-Belapur','CBD Belapur',regex=True)
df['REGION'] = df['REGION'].str.replace('Girgaon Chowpatty','Chowpatty',regex=True)
df['REGION'] = df['REGION'].str.replace('Dadar Shivaji Park','Dadar',regex=True)
df['REGION'] = df['REGION'].str.replace('Flea Bazaar Café|Kamala Mills Compound','Lower Parel',regex=True)
df['REGION'] = df['REGION'].str.replace('Runwal Green','Mulund',regex=True)
df['REGION'] = df['REGION'].str.replace('Mumbai CST Area','Mumbai Central',regex=True)
df['REGION'] = df['REGION'].str.replace('Kopar Khairane|Seawoods|Turbhe|Ulwe','Navi Mumbai',regex=True)
df['REGION'] = df['REGION'].str.replace('New Panvel|Old Panvel','Panvel',regex=True)
df['REGION'] = df['REGION'].str.replace('Kamothe','Sion',regex=True)
df['REGION'] = df['REGION'].str.replace('Ghodbunder Road|Majiwada','Thane',regex=True)

In [34]:
# removing duplicate records

df[df.duplicated()]

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
4064,Sai Sannidhi Restaurant & Bar,1000,"North Indian,Konkan",dahisar,Casual Dining,11am to 12midnight,Good,3.7,99.0,Mon-Sun
4068,Konkan Katta,400,"Seafood,Maharashtrian,Malwani",mahakali,Quick Bites,"11am to 330pm,630pm to 1130pm",Good,3.5,181.0,Mon-Sun
4082,Usmaniya Hotel,600,Mughlai,fort,Casual Dining,1030am to 1130pm,Average,3.2,8.0,Mon-Sun
4083,Gina's Cakes,450,Bakery,dombivali,none,11am to 11pm,Good,3.5,49.0,Mon-Sun
4084,Konkanastha Lunch Home,400,"Seafood,Malwani",chakala,Casual Dining,"12noon to 3pm,730pm to 1030pm",Good,3.5,44.0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
14200,Mezbaan Family Restaurant,350,"Chinese,Mughlai",mumbra,Dhaba,12noon to 1230AM,Average,2.8,97.0,Mon-Sun
14204,Jyoti Lunch Home,650,"Chinese,North Indian,Seafood,Mughlai",mulund,Casual Dining,11am to 1230AM,Good,3.5,49.0,Mon-Sun
14253,On Toes,900,"Italian,North Indian,Chinese",malad,Casual Dining,"12noon to 3pm,7pm to 1230AM",Good,3.6,76.0,Mon-Sun
14761,Frosty Farm,400,"Ice Cream,Desserts,Fast Food",malad,Dessert Parlor,1pm to 1215AM,Good,3.6,120.0,Mon-Sun
14928,Shree Manu Sagar,300,"North Indian,Chinese,Indian",ghansoli,Quick Bites,"1130am to 415pm,7pm to 1215AM",Average,3.3,51.0,Mon-Sun

In [35]:
df = df.drop_duplicates()

In [36]:
# copying cleaned data into new dataframe
zomato_df = df.copy()
zomato_df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",bandra kurla complex,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
3,Butterfly High,1000,Modern Indian,bandra kurla complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",bandra kurla complex,Bar,1130am to 1am,Very Good,4.4,5995.0,Mon-Sun

In [37]:
# saving the cleaned data into new csv file

import joblib

joblib.dump(zomato_df, 'files/Preprocessed_zomato_dataset.csv')

['files/Preprocessed_zomato_dataset.csv']